version: '3'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - rails-devise-bootstrap_default

  app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - rails-devise-bootstrap_default

networks:
  rails-devise-bootstrap_default:
    driver: bridge
