default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
development:
  <<: *default
  database: online_chat_development

test:
  <<: *default
  database: online_chat_test

production:
  <<: *default
  database: online_chat_production
